export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_GLOBAL = 'FETCH_GLOBAL';
export const FETCH_LAST_UPDATED = 'FETCH_LAST_UPDATED';
export const FETCH_HISTORY = 'FETCH_HISTORY';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';