export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_GLOBAL = 'FETCH_GLOBAL';
export const FETCH_HISTORY_CONFIRMED = 'FETCH_HISTORY_CONFIRMED';
export const FETCH_HISTORY_RECOVERED = 'FETCH_HISTORY_RECOVERED';
export const FETCH_HISTORY_DEATHS = 'FETCH_HISTORY_DEATHS';
